import { useState, useMemo, useEffect, useRef } from 'react';
import { parseISO, eachDayOfInterval, getDay, format, startOfMonth, endOfMonth, startOfWeek, endOfWeek, isSameDay, isWithinInterval } from "date-fns";
import { Copy, Check, ChevronDown, Calendar } from "lucide-react";

const CFG = { terms: { term_1: { start: "2026-01-28", end: "2026-04-02" }, term_2: { start: "2026-04-20", end: "2026-06-26" }, term_3: { start: "2026-07-13", end: "2026-09-18" }, term_4: { start: "2026-10-05", end: "2026-12-18" } }, holidays: [{ name: "Labor Day", date: "2026-03-09" }, { name: "Anzac Day", date: "2026-04-25" }, { name: "King's Birthday", date: "2026-06-08" }, { name: "Melbourne Cup", date: "2026-11-03" }], levels: { prep_6: { label: "GRADE PREP-6", rates: { new: 85, loyalty: 75 } }, grade_7_10: { label: "GRADE 7-10", rates: { new: 98, loyalty: 82 } }, vce: { label: "VCE", rates: { new: 120, loyalty: 95 } }, adult: { label: "ADULT", rates: { new: 140, loyalty: 110 } } }, discounts: [0, 100, 0, 300], durations: { "45_min": 0.75, "1_hour": 1, "1.5_hours": 1.5, "2_hours": 2 } },
  DAY_MAP = { Sunday: 0, Monday: 1, Tuesday: 2, Wednesday: 3, Thursday: 4, Friday: 5, Saturday: 6 } as const, TERMS = ["term_1", "term_2", "term_3", "term_4"] as const, DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"] as const, DURATIONS = ["45_min", "1_hour", "1.5_hours", "2_hours"] as const, DUR_LABELS = { "45_min": "45 MIN", "1_hour": "1 HR", "1.5_hours": "1.5 HR", "2_hours": "2 HR" } as const,
  INPUT = "w-full px-4 py-3 bg-black border border-zinc-800 text-white text-sm focus:outline-none focus:border-white appearance-none [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:appearance-none", BTN_ON = "bg-white text-black", BTN_OFF = "bg-black border border-zinc-800 text-zinc-400 hover:text-white";

type TermKey = typeof TERMS[number];
type DayOfWeek = typeof DAYS[number];
type DurationKey = typeof DURATIONS[number];
type LevelKey = keyof typeof CFG.levels;
type TermConfig = { dayOfWeek: DayOfWeek; duration: DurationKey; startDate?: string; endDate?: string };

const useClickAway = (ref: React.RefObject<HTMLElement | null>, open: boolean, setOpen: (open: boolean) => void) => useEffect(() => { if (!open) return; const close = (e: MouseEvent) => ref.current?.contains(e.target as Node) || setOpen(false), esc = (e: KeyboardEvent) => e.key === 'Escape' && setOpen(false);
  document.addEventListener('mousedown', close); document.addEventListener('keydown', esc); return () => { document.removeEventListener('mousedown', close); document.removeEventListener('keydown', esc); }; }, [ref, open, setOpen]);

function Dropdown({ value, options, onChange, open, setOpen, label, Icon = ChevronDown }: { value: string; options: Array<{ value: string; label: string }>; onChange: (value: string) => void; open: boolean; setOpen: (open: boolean) => void; label: string; Icon?: React.ComponentType<{ className?: string }> }) {
  const ref = useRef<HTMLDivElement>(null); useClickAway(ref, open, setOpen);
  return <div className="relative" ref={ref}><button onClick={() => setOpen(!open)} className={`${INPUT} flex items-center justify-between`} aria-label={label}>{value}<Icon className="h-4 w-4" /></button>
    {open && <div className="absolute z-50 w-full mt-1 bg-black border border-zinc-800">{options.map(o => <button key={o.value} onClick={() => (onChange(o.value), setOpen(false))} className={`w-full px-4 py-3 text-left text-sm hover:bg-zinc-900 ${value === o.label ? BTN_ON : ""}`}>{o.label}</button>)}</div>}</div>;
}

function CalendarPicker({ value, onChange, min, max, label }: { value?: string; onChange: (date: string) => void; min: string; max: string; label: string }) {
  const [open, setOpen] = useState(false), [month, setMonth] = useState(() => value ? parseISO(value) : parseISO(min)), ref = useRef<HTMLDivElement>(null); useClickAway(ref, open, setOpen);
  const minDate = parseISO(min), maxDate = parseISO(max), selectedDate = value ? parseISO(value) : null, days = eachDayOfInterval({ start: startOfWeek(startOfMonth(month), { weekStartsOn: 1 }), end: endOfWeek(endOfMonth(month), { weekStartsOn: 1 }) }),
    isHoliday = (d: Date) => CFG.holidays.some(h => isSameDay(d, parseISO(h.date))), changeMonth = (dir: number) => setMonth(d => { const n = new Date(d); n.setMonth(n.getMonth() + dir); return n; });
  return <div className="relative" ref={ref}><button onClick={() => setOpen(!open)} className={`${INPUT} flex items-center justify-between`} aria-label={label}>{value ? format(parseISO(value), "d MMM yyyy") : "Select date"}<Calendar className="h-4 w-4" /></button>
    {open && <div className="absolute z-50 mt-1 bg-black border border-zinc-800 p-4 w-80"><div className="flex items-center justify-between mb-4">
      <button onClick={() => changeMonth(-1)} className="px-2 py-1 text-zinc-400 hover:text-white">‹</button><div className="text-sm font-medium">{format(month, "MMMM yyyy")}</div>
      <button onClick={() => changeMonth(1)} className="px-2 py-1 text-zinc-400 hover:text-white">›</button></div>
      <div className="grid grid-cols-7 gap-1 mb-2">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map(d => <div key={d} className="text-xs text-zinc-400 text-center py-1">{d}</div>)}</div>
      <div className="grid grid-cols-7 gap-1">{days.map(d => { const disabled = !isWithinInterval(d, { start: minDate, end: maxDate }), isSelected = selectedDate && isSameDay(d, selectedDate);
        return <button key={d.toISOString()} onClick={() => !disabled && (onChange(format(d, "yyyy-MM-dd")), setOpen(false))} disabled={disabled}
          className={`p-2 text-xs ${disabled ? "text-zinc-800 cursor-not-allowed" : isSelected ? BTN_ON : isHoliday(d) ? "text-zinc-500" : "text-zinc-400 hover:text-white hover:bg-zinc-900"}`}>{format(d, "d")}</button>; })}</div></div>}</div>;
}

export function TermCalculator() {
  const [clientType, setClientType] = useState<"loyalty" | "new_client">("loyalty"), [studentLevel, setStudentLevel] = useState<LevelKey>("grade_7_10"), [selectedTerms, setSelectedTerms] = useState<TermKey[]>([]),
    [termConfigs, setTermConfigs] = useState<Partial<Record<TermKey, TermConfig>>>({}), [creditAmount, setCreditAmount] = useState(0), [copied, setCopied] = useState(false), [openDropdown, setOpenDropdown] = useState<string | null>(null);
  const calc = useMemo(() => { if (!selectedTerms.length) return { termDetails: [], baseCost: 0, subtotal: 0, appliedDiscount: 0, discountLabel: "", credit: 0, total: 0, loyaltySaving: 0, tape: "" };
    const level = CFG.levels[studentLevel], rate = clientType === "loyalty" ? level.rates.loyalty : level.rates.new, appliedDiscount = CFG.discounts[selectedTerms.length - 1] || 0, discountLabel = selectedTerms.length === 4 ? "ANNUAL DISCOUNT" : selectedTerms.length === 2 ? "MULTI-TERM DISCOUNT" : "";
    const processTerms = (calcRate: number) => selectedTerms.reduce((acc, term) => { const cfg = termConfigs[term]; if (!cfg) return acc; const { start: tStart, end: tEnd } = CFG.terms[term], termStart = parseISO(tStart), termEnd = parseISO(tEnd), start = cfg.startDate ? parseISO(cfg.startDate) : termStart, end = cfg.endDate ? parseISO(cfg.endDate) : termEnd, dates: string[] = [], holidays: string[] = []; let lessons = 0;
      eachDayOfInterval({ start: termStart, end: termEnd }).filter(d => getDay(d) === DAY_MAP[cfg.dayOfWeek]).forEach(d => { const dStr = format(d, "yyyy-MM-dd"), holiday = CFG.holidays.find(h => h.date === dStr); if (holiday) holidays.push(holiday.name.toUpperCase()); else if ((!cfg.startDate || d >= start) && (!cfg.endDate || d <= end)) { lessons++; dates.push(dStr); } });
      acc.termDetails.push({ term, dayOfWeek: cfg.dayOfWeek, duration: cfg.duration, lessons, dates, holidays }); acc.baseCost += calcRate * lessons * CFG.durations[cfg.duration]; return acc; }, { termDetails: [] as Array<{ term: TermKey; dayOfWeek: DayOfWeek; duration: DurationKey; lessons: number; dates: string[]; holidays: string[] }>, baseCost: 0 });
    const { termDetails, baseCost } = processTerms(rate), credit = creditAmount || 0, subtotal = Math.round(baseCost - appliedDiscount), total = Math.max(0, subtotal - credit), loyaltySaving = clientType === "new_client" ? total - Math.max(0, Math.round(processTerms(level.rates.loyalty).baseCost - appliedDiscount) - credit) : 0, sorted = [...termDetails].sort((a, b) => a.term.localeCompare(b.term)), rateLabel = clientType === "loyalty" ? `${level.label} LOYALTY` : level.label,
      termLines = sorted.map((td, i) => [`TERM ${td.term.split("_")[1]}`, td.dates.length ? `${format(parseISO(td.dates[0]), "d MMM").toUpperCase()} — ${format(parseISO(td.dates[td.dates.length - 1]), "d MMM").toUpperCase()}` : "", `${td.lessons} SESSIONS / ${DUR_LABELS[td.duration]}`, td.holidays.length ? `EXCLUDES: ${td.holidays.join(", ")}` : null, i < sorted.length - 1 ? "---" : null].filter(Boolean).join("\n")),
      tapeLines = [rateLabel, "", ...termLines, "", `SUBTOTAL $${Math.round(baseCost).toLocaleString()}`, appliedDiscount > 0 ? `${discountLabel} -$${appliedDiscount.toLocaleString()}` : null, credit > 0 ? `CREDIT -$${credit.toLocaleString()}` : null, `PAYABLE $${total.toLocaleString()}`, clientType === "new_client" && loyaltySaving > 0 ? "" : null, clientType === "new_client" && loyaltySaving > 0 ? `RELATIONSHIP MILESTONE: YOU WILL AUTOMATICALLY TRANSITION TO OUR LOYALTY TIER IN TERM 2, REDUCING YOUR NEXT TERM INVESTMENT BY $${loyaltySaving.toLocaleString()}.` : null];
    return { termDetails: sorted, baseCost: Math.round(baseCost), subtotal, appliedDiscount, discountLabel, credit, total, loyaltySaving, tape: tapeLines.filter(Boolean).join("\n") }; }, [selectedTerms, termConfigs, studentLevel, clientType, creditAmount]);
  const toggleTerm = (term: TermKey) => { if (selectedTerms.includes(term)) { setSelectedTerms(selectedTerms.filter(t => t !== term)); const { [term]: _, ...rest } = termConfigs; setTermConfigs(rest); }
    else { setSelectedTerms([...selectedTerms, term]); setTermConfigs({ ...termConfigs, [term]: selectedTerms.length > 0 && termConfigs[selectedTerms[0]] ? termConfigs[selectedTerms[0]] : { dayOfWeek: "Monday", duration: "1_hour" } }); } };
  return <main className="h-[100dvh] overflow-hidden bg-black text-white flex flex-col landscape:flex-row md:flex-row landscape:gap-24 pb-[safe-area-inset-bottom]">
    <div className="flex-1 max-w-md p-8 md:p-12 space-y-4 overflow-y-auto order-1 landscape:order-1 landscape:text-xs">
      <h1 className="text-7xl font-black tracking-tighter landscape:text-3xl" style={{ letterSpacing: '-0.05em' }}>Term Calculator</h1>
      <div className="flex gap-2">{(["loyalty", "new_client"] as const).map(type => <button key={type} onClick={() => setClientType(type)} className={`flex-1 px-4 py-3 text-sm font-medium transition-colors landscape:text-xs ${clientType === type ? BTN_ON : BTN_OFF}`}>{type === "loyalty" ? "LOYALTY" : "NEW CLIENT"}</button>)}</div>
      <Dropdown value={CFG.levels[studentLevel].label} options={Object.entries(CFG.levels).map(([key, level]) => ({ value: key, label: level.label }))} onChange={(key) => setStudentLevel(key as LevelKey)} open={openDropdown === "level"} setOpen={o => setOpenDropdown(o ? "level" : null)} label="Select grade level" />
      <div className="grid grid-cols-2 gap-2">{TERMS.map(term => <button key={term} onClick={() => toggleTerm(term)} aria-label={`Toggle Term ${term.split("_")[1]}`} className={`px-4 py-3 text-sm font-medium transition-colors landscape:text-xs ${selectedTerms.includes(term) ? BTN_ON : BTN_OFF}`}>TERM {term.split("_")[1]}</button>)}</div>
      {selectedTerms.length > 0 && <div className="space-y-2">{[...selectedTerms].sort().map(term => { const cfg = termConfigs[term]; if (!cfg) return null; const termNum = term.split("_")[1], update = (u: Partial<TermConfig>) => setTermConfigs({ ...termConfigs, [term]: { ...cfg, ...u } });
        return <div key={term} className="border border-zinc-800"><button onClick={() => setOpenDropdown(openDropdown === term ? null : term)} className="w-full px-4 py-3 flex items-center justify-between text-left hover:bg-zinc-900 transition-colors"><span className="font-medium text-sm landscape:text-xs">TERM {termNum}</span><span className="text-zinc-400 text-xs">{(openDropdown === term || openDropdown?.startsWith(`${term}-`)) ? "−" : "+"}</span></button>
          {(openDropdown === term || openDropdown?.startsWith(`${term}-`)) && <div className="px-4 pb-4 space-y-3 border-t border-zinc-800 pt-4"><Dropdown value={cfg.dayOfWeek.toUpperCase()} options={DAYS.map(d => ({ value: d, label: d.toUpperCase() }))} onChange={(day) => update({ dayOfWeek: day as DayOfWeek })} open={openDropdown === `${term}-day`} setOpen={o => setOpenDropdown(o ? `${term}-day` : null)} label={`Select day for Term ${termNum}`} />
            <Dropdown value={DUR_LABELS[cfg.duration]} options={DURATIONS.map(d => ({ value: d, label: DUR_LABELS[d] }))} onChange={(d) => update({ duration: d as DurationKey })} open={openDropdown === `${term}-dur`} setOpen={o => setOpenDropdown(o ? `${term}-dur` : null)} label={`Select duration for Term ${termNum}`} /><button onClick={() => setOpenDropdown(openDropdown === `${term}-dates` ? null : `${term}-dates`)} className="w-full px-3 py-2 text-xs text-zinc-400 hover:text-white transition-colors text-left">CUSTOM DATES {openDropdown === `${term}-dates` ? "−" : "+"}</button>
            {openDropdown === `${term}-dates` && <div className="space-y-2 pl-4 border-l border-zinc-800"><CalendarPicker value={cfg.startDate} onChange={(d) => update({ startDate: d })} min={CFG.terms[term].start} max={CFG.terms[term].end} label={`Start date for Term ${termNum}`} /><CalendarPicker value={cfg.endDate} onChange={(d) => update({ endDate: d })} min={CFG.terms[term].start} max={CFG.terms[term].end} label={`End date for Term ${termNum}`} /></div>}</div>}</div>; })}</div>}
      <input type="number" step="0.01" min="0" value={creditAmount || ""} onChange={e => setCreditAmount(parseFloat(e.target.value) || 0)} placeholder="CREDIT" aria-label="Apply credit amount" className={`${INPUT} placeholder:text-zinc-400`} />
      <div className="text-[10px] text-white text-center pt-4">{(import.meta.env.VITE_COMMIT_REF || import.meta.env.VITE_GIT_COMMIT_SHA)?.substring(0, 7) || 'dev'}</div></div>
    <div className="flex-1 max-w-md p-8 md:p-12 flex flex-col items-center justify-center gap-12 md:gap-16 order-2 landscape:order-2 landscape:sticky landscape:top-0 landscape:self-start min-h-0">{!calc.termDetails.length ? <div className="text-9xl font-black tracking-tighter text-zinc-900 landscape:text-5xl">0</div> : <div className="w-full space-y-6 md:space-y-8 landscape:space-y-3">
        <div className="text-lg md:text-xl font-black uppercase tracking-wider landscape:text-sm">{clientType === "loyalty" ? `${CFG.levels[studentLevel].label} LOYALTY` : CFG.levels[studentLevel].label}</div>
        <div className="space-y-6 md:space-y-8 landscape:space-y-3">{calc.termDetails.map((td, i) => <div key={td.term} className="space-y-2"><div className="text-xl md:text-2xl font-black uppercase landscape:text-sm">TERM {td.term.split("_")[1]}</div>
          {td.dates.length > 0 && <div className="text-xl font-light text-zinc-400 landscape:text-xs">{format(parseISO(td.dates[0]), "d MMM").toUpperCase()} — {format(parseISO(td.dates[td.dates.length - 1]), "d MMM").toUpperCase()}</div>}
          <div className="text-xl font-light text-zinc-400 landscape:text-sm">{td.lessons} SESSIONS / {DUR_LABELS[td.duration]}</div>{td.holidays.length > 0 && <div className="text-xl font-light text-zinc-400 landscape:text-sm">EXCLUDES: {td.holidays.join(", ")}</div>}
          {i < calc.termDetails.length - 1 && <div className="text-xl font-light text-zinc-400 pt-3">---</div>}</div>)}</div>
        <div className="space-y-3 pt-6 md:pt-8 border-t border-zinc-800"><div className="text-lg md:text-xl font-black landscape:text-sm">SUBTOTAL ${calc.baseCost.toLocaleString()}</div>
          {calc.appliedDiscount > 0 && <div className="text-lg md:text-xl font-black landscape:text-sm">{calc.discountLabel} -${calc.appliedDiscount.toLocaleString()}</div>}{calc.credit > 0 && <div className="text-lg md:text-xl font-black landscape:text-sm">CREDIT -${calc.credit.toLocaleString()}</div>}
          <div className="text-9xl font-black tracking-tighter pt-4 md:pt-6 landscape:text-4xl">${calc.total.toLocaleString()}</div></div>
        {clientType === "new_client" && calc.loyaltySaving > 0 && <div className="text-sm md:text-base font-light text-zinc-400 pt-4 md:pt-6 border-t border-zinc-800">RELATIONSHIP MILESTONE: YOU WILL AUTOMATICALLY TRANSITION TO OUR LOYALTY TIER IN TERM 2, REDUCING YOUR NEXT TERM INVESTMENT BY ${calc.loyaltySaving.toLocaleString()}.</div>}
        <button onClick={() => { navigator.clipboard.writeText(calc.tape).catch(() => {}); setCopied(true); setTimeout(() => setCopied(false), 2000); }} aria-label="Copy calculation to clipboard" className="p-2 border border-zinc-800 hover:border-white transition-colors">{copied ? <Check className="h-4 w-4 text-white" /> : <Copy className="h-4 w-4 text-zinc-400" />}</button></div>}</div></main>;
}